### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#10]
The one thing I think will help this project is a readme with a comprehensive index of the questions present in this repo (or even a separate file for index will do great). 

Some areas where we could work - 
1. Add a logo
2. Improve the language
3. Usage instructions
4. Make readme more comprehensive and friendly

Feel free to suggest any ideas or suggestions and file a PR :smiley:

**Comment by tehtbl** [comment]
Hi @prabhupant 

what do you mean by beautifying? Do you wanna some emoticons? Some buttons? A TOC?

Please tell me and I can support you.

cheers,
Thomas

**Comment by prabhupant** [comment]
Hey @tehtbl 

Thanks for pointing out that the issue description wasn't clear :smiley: 

Please refer to it. I have made some changes.
