### ISSUE TITLE
update and link files in index.md 

### ISSUE THREAD

**Issue by shreyas1599** [prabhupant/python-ds#105]
The index.md file within sub-folders which lists the names of files within the sub-folder don't have links to them and some of the index.md 's don't have the list of all files within the sub folder. 
For example, the following link:

https://github.com/prabhupant/python-ds/blob/master/data_structures/binary_trees/index.md
does not have a link to the file listed in it. 

Can I work on this?

**Comment by prabhupant** [comment]
Sure, go ahead!

**Comment by shreyas1599** [comment]
I've submitted a PR. Instead of the file names as contents in the index, I listed them as topics(removed the .py extension, replaced underscores with spaces and capitalised first letter of every word). Maybe I could update the index_updater script to reflect this change? I was not aware that there was already an updater script in place.
