### ISSUE TITLE
Add link to useful_links.md in readme

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#13]

**Comment by hacky1997** [comment]
What I have to do? I mean what type of useful links I can add for you?

**Comment by prabhupant** [comment]
Hi @hacky1997 

Any link that is good and increases knowledge. Please refer to the various links in that file to get an idea

**Comment by jotaro-sama** [comment]
Hi! I added an interesting link about linear time sorting algorithms, which may be a question in tests or interviews. Check it out in my PR: #80

**Comment by prabhupant** [comment]
Hey @jotaro-sama 

That link was interesting! Merged it :+1: 
Thanks for the PR :smiley:
