### ISSUE TITLE
Add new questions for graphs

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#17]
Please add more graph questions. Let's help those in need for interview preparations :smiley:

**Comment by Oishika-Pradhan** [comment]
Would like to add some questions. Hope that's okay.

**Comment by prabhupant** [comment]
@Oishika-Pradhan Please do! Contributions are always welcomed :smiley:

**Comment by mallapraveen** [comment]
@prabhupant 
would like to add some questions.

**Comment by prabhupant** [comment]
@mallapraveen Sure go ahead :beers:
