### ISSUE TITLE
Use of built in functions names as variables

### ISSUE THREAD

**Issue by MomIsBestFriend** [prabhupant/python-ds#170]
I saw that in files:
```
data_structures/array/all_numbers_divisible.py
data_structures/array/max_consecutive_ones.py
data_structures/bst/check_if_bt_if_bst.py
```
There is a use of the words ```min``` and ```max``` as variables.
```min``` and ```max``` are builtin functions of python and should not be used as variables.

**Comment by prabhupant** [comment]
Using builtin names as variable names is not a good practice but for our case it is as the focus is to bring home the idea of the underlying algorithm
