### ISSUE TITLE
Add new questions for stack

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#18]
Please add more stack questions. Let's help those in need for interview preparations :smiley:

**Comment by vAporInside** [comment]
I would love to add stack questions :)

**Comment by prabhupant** [comment]
Hi @vAporInside Welcome

Feel free to file any PR :)

**Comment by vAporInside** [comment]
Already added PR: "Added stack problems" 😊

**Comment by AayushG159** [comment]
I would love to add more stack questions. Will raise PR when done

**Comment by prabhupant** [comment]
@AayushG159 Sure, go ahead! :smiley:

**Comment by nandadeepd** [comment]
Hey, I was wondering if I can add some stack questions as well.

**Comment by prabhupant** [comment]
Yeah sure :)

**Comment by FARVE14** [comment]
Hi @prabhupant , I'd like to contribute to this.  I can add the question to implement a stack using linked list.  Thanks!

**Comment by prabhupant** [comment]
@FARVE14 go ahead :+1:
