### ISSUE TITLE
Add new questions for heaps

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#20]
Please add more heaps questions. Let's help those in need for interview preparations :smiley:

**Comment by Kuljeet-123** [comment]
@prabhupant I would like to work on this

**Comment by prabhupant** [comment]
@Kuljeet-123 Go ahead! :beers:

**Comment by Kuljeet-123** [comment]
@prabhupant  please review my PR and merge into your repo and my PR id is #75 .Thanks!!.

**Comment by prabhupant** [comment]
@Kuljeet-123 I have reviewed it. Please have a look :)

**Comment by Minor-lazer** [comment]
i Want to work on it

**Comment by prabhupant** [comment]
Go ahead
