### ISSUE TITLE
Add new questions for binary trees

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#21]
Please add more binary trees questions. Let's help those in need for interview preparations :smiley:

**Comment by sainimohit23** [comment]
Hi @prabhupant ,
I stumbled upon this repository while browsing hacktoberfest related issues on github. I am in final year of my college and these days I am practicing algorithms a lot. I am also contributing other repositories which collect the solutions for interviewbit questions. So, I would also like to contribute to this repository.

Before contributing I just want to know little bit about how Hacktoberfest work. I went to their website to understand this program, but still I have doubts about it.

**Comment by JayWelborn** [comment]
For questions, do you want question + answer, or just the question?

**Comment by prabhupant** [comment]
Hi @JayWelborn 

Please write the file name as 3-4 words indicating the question/problem, like for finding the max in linked list, the file name would be `max_in_linked_list.py` and inside this the solution. You can refer to the files in this repo to have an idea

**Comment by prabhupant** [comment]
Hi @sainimohit23 

Its nice that you are looking forward to contribute to this repo :beers:

Hacktoberfest is basically a program organised by DigitalOcean, GitHub and other organisations to promote open source and to give an initiative to those looking to start contributing to open source. The way this program works is,  you first need to signup here https://hacktoberfest.digitalocean.com with your github credentials and then make 4 PRs in any public repo, not necessarily those with the `hacktoberfest` tag. That's all! And you get a free t-shirt!

**Comment by suresh4041** [comment]
Hshjs
