### ISSUE TITLE
Add new questions for strings

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#23]
Please add more string questions. Let's help those in need for interview preparations :smiley:

**Comment by BiaHawk** [comment]
do you want questions that are made in interviews? and Can I add those questions directly on questions to do?

**Comment by prabhupant** [comment]
@BiaHawk we need questions that are quite often asked in interviews or those that explore strings logic and techniques or some interesting questions. Sure if you want to create a new file called `questions to do`, file a PR :smiley: 
Just be sure to make it a markdown file as they look good on GitHub :)

**Comment by brilam** [comment]
I've added a string question from Cracking the Code Interview (Q 1.2). Could you please review my changes and if it is good, could your merge it? Thanks. :)

**Comment by prabhupant** [comment]
Hi @brilam 

I have reviewed and merged the PR. Thanks :smile:

**Comment by AnilKumarTeegala** [comment]
Toggle String Question added #91
