### ISSUE TITLE
Interesting sorting algorithms

### ISSUE THREAD

**Issue by hugoecarl** [prabhupant/python-ds#249]

**Comment by hugoecarl** [comment]
I have an interest in sorting algorithms, already done a PR for bucket sort #250 that i think it's important and cool, any more to add in repo? A list for me and others to work would be interesting.

**Comment by aadityachapagain** [comment]
Hey @hugoecarl  you can add some of interesting algorithms here https://github.com/aadityachapagain/Descent_py   .Last week i created several PR in this repo but none were merged. There was no merge conflicts and every criteria was posed well but I found my PR closed for no reasons.
 we can try adding at mine if you are interested thanks.

**Comment by JvPy** [comment]
What about radix sort? I would like to write it.
