### ISSUE TITLE
Max width of binary tree.

### ISSUE THREAD

**Issue by doshi-parth** [prabhupant/python-ds#334]
I would like to submit a solution to this question. Please assign me this task.

**Comment by prabhupant** [comment]
Sure, go ahead

**Comment by Varun270** [comment]
Hi , actually I am new to open source and don't know how to solve any issue, can someone please guide me.

**Comment by prabhupant** [comment]
Hi @Varun270 
Apologies for the late reply. You can start with improving any older code (like cleaning the code, providing a better solution) or add a new question. You can refer to this https://github.com/prabhupant/python-ds/blob/master/CONTRIBUTING.md to get a head start about open source contribution

**Comment by Varun270** [comment]
Hello, @prabhupant  thanks for replying I have generated a new pull request and added a new queue problem please go through it and merge it.
