### ISSUE TITLE
Create an index.md file for every sub-directory

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#34]
Having an index for every sub-directory will ease navigation around the repository. Here is the structure I think will do good

```
- Data Structures
   - array
      - index.md
   - stack
      - index.md
```
and so on.

Please feel free to suggest improvements anywhere you feel like and contribute :smiley:

**Comment by KristoferSoler** [comment]
@prabhupant , ¿so you want all the existing files of X subdirectory in the index.md?

**Comment by prabhupant** [comment]
@KristoferSoler Yes. Reading names of files/questions in index.md will be a lot easier as compared to reading them from directories

**Comment by KristoferSoler** [comment]
Okay, I will make a PR asap between today and tomorrow. :smile:

**Comment by prabhupant** [comment]
@KristoferSoler Great! PRs are welcomed anytime :)

**Comment by KristoferSoler** [comment]
Dude, ¿how I can upload the PR? I follow the instructions on the readme but doesn't work. It says "Permission to prabhupant/python-ds.git denied to KristoferSoler". :cry:

**Comment by KristoferSoler** [comment]
@prabhupant you should close this if it's done xD

**Comment by prabhupant** [comment]
@KristoferSoler I totally forgot :sweat_smile:
