### ISSUE TITLE
Create mkdocs or readthedocs explaining all data structures

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#36]
This is a big goal and will definitely take months. But if we want this repository to be a single source for interview prep and studying about data structures and algorithms, then having a comprehensive doc about each data structure with its theory like time complexities and use cases will definitely be a great thing.

I will start working on this in order to give it some direction and momentum. 

Please feel free to suggest any improvements, open issues, point my short comings or contribute :smiley:

**Comment by srbhr** [comment]
@prabhupant , How are you going to start this ?
Say make a website first(xyz.github.io) and then host MKDocs from there ??

**Comment by simonbcodes** [comment]
@prabhupant @srbhr 

The documentation could be hosted through readthedocs (https://readthedocs.org/). They have free hosting and can automatically rebuild documentation whenever something is pushed to this repo. They've got a guide to setting it up here:

https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by srbhr** [comment]
@simonbcodes Was thinking of some way, but before that. This repository needs some more organisation. And I'm thinking of adding Python tricks as well!!
@prabhupant Can we have a python tricks section and put some jupyter notebooks there. Jupyter Notebooks are also a great way to do stuff!! We can explain at the moment with code there!

**Comment by prabhupant** [comment]
@simonbcodes Yeah, right. Readthedocs provides free hosting for open source projects and that will be the best way for this. Let's first let the repository mature a bit more in this week and we can pick this up from this weekend.

**Comment by prabhupant** [comment]
@srbhr That is a nice feature and we can implement it at some later time when the repository has matured :)
