### ISSUE TITLE
Factorial function not implemented in algorithm/math directory

### ISSUE THREAD

**Issue by hbarua05** [prabhupant/python-ds#377]
Add two files with functions that get factorial of a given number. 
One with an iterative method and other with a recursive method.

**Comment by sugato1398** [comment]
hi, I am new to contributing to open source , I would like to take this issue if its open

**Comment by hbarua05** [comment]
> hi, I am new to contributing to open source , I would like to take this issue if its open

Sure, that would be great! But I would like to point out tho that somebody has already made a pull request regarding this issue.

**Comment by sugato1398** [comment]
yeah, i saw that later, ill look up for other issues, thanks
