### ISSUE TITLE
Create a logo for the repository's readme

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#38]
The readme will look better with a logo. We just need a minimalist and simple logo (only text) with the words `python-ds`.

Feel free to file a PR :smiley:

**Comment by hacky1997** [comment]
I want to work on this please.

**Comment by prabhupant** [comment]
Hi @hacky1997 
Sure, go ahead and file a PR :smiley:

**Comment by srbhr** [comment]
Made a simple logo, have a look!
https://www.canva.com/design/DADnmqi24cA/Yi1oyWv9zA3T4WCFUbCgbw/view?utm_content=DADnmqi24cA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by prabhupant** [comment]
@srbhr Thanks for the PR. Please make a minimalist logo with a very simple image or just take based :smiley:

**Comment by srbhr** [comment]
Will any of these do ?

**Comment by Akashd7** [comment]
@prabhupant Check My PR.Added a MiniMalist Logo.

**Comment by prabhupant** [comment]
@srbhr This one looks good https://www.canva.com/design/DADnmtPXeCc/Xx-SHwYVnIbasCfBTKbfnQ/view?utm_content=DADnmtPXeCc&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Just change the text to `python-ds` and make it right next to the image, all in a single horizontal line :)

**Comment by prabhupant** [comment]
Closed via #55
