### ISSUE TITLE
Pythonic code

### ISSUE THREAD

**Issue by allentv** [prabhupant/python-ds#385]
Thanks for creating a collection of Python solutions. Most of the code seems to be a direct translation of a C++/Java program and not being pythonic. Simple example would be to use list comprehensions instead of appending elements to a list with a while loop. Would you be interested in PRs that refactor code to be more `Pythonic`?

**Comment by divykj** [comment]
Hey, I would love to refactor the code in a more Pythonic fashion, could you point out some pieces of code to start with?
