### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by allentv** [prabhupant/python-ds#386]
It is nice to have solutions but I am missing the context of how inputs would be transformed by algorithms and data structures. If there were unit tests that describe different inputs and expected outputs, that would make the learning process more contextual. Thoughts?

**Comment by Ask-Subhasmita** [comment]
hey, @allentv I would like to work on this issue, could help me with being specific to add test cases to which algorithms or any particular algorithm?

**Comment by allentv** [comment]
I would prefer to have test cases for all algorithms to have context. I have been using `unittest` package for creating test cases. Here is an example : https://docs.python.org/3/library/unittest.html#basic-example
