### ISSUE TITLE
Iterative and Recursive approach for Inorder Traversal of a Binary Tree.

### ISSUE THREAD

**Issue by sachinnegi** [prabhupant/python-ds#401]
Hi, I would like to add a solution for inorder traversal of binary tree using recursion and iteration.

**Comment by ExpressHermes** [comment]
I would like to work on this issue.

**Comment by Rasesh2005** [comment]
is this solved or still open??

**Comment by Varun270** [comment]
@Rasesh2005  Bro I think It is still open
