### ISSUE TITLE
[readme][broken link] 

### ISSUE THREAD

**Issue by Nakamcode** [prabhupant/python-ds#450]
The Dictionary link under the data structures section is broken

**Comment by vintagemind** [comment]
@Nakamcode There isn't a Dictionary link under the data structures section though, or am I missing something?

**Comment by ROMEEZHOU** [comment]
I believe Nakamcode is describing the link of "dictionary" under the section "Data Structure" in readme. I tried it and it is broken.
<img width="734" alt="Screen Shot 2023-03-27 at 22 18 15" src="https://user-images.githubusercontent.com/72342196/227967451-c7471b91-726c-4bfb-8a6b-2bdba408285a.png">
