### ISSUE TITLE
Adding searching algorithms

### ISSUE THREAD

**Issue by ThanasisMpalatsoukas** [prabhupant/python-ds#65]
I would like to contribute to this repository by making **searching algorithms** for python in the ### algorithm subfolder _( My first contribution )_.

**Comment by prabhupant** [comment]
Hi @ThanasisMpalatsoukas 

Welcome! Sure, go ahead. Contributions are always welcomed :beers:

**Comment by naumanahmad9** [comment]
I would like to contribute to this repository

**Comment by Tyred** [comment]
I would like to contribute c:
