### ISSUE TITLE
Changes in useful_links.md

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#87]
To ease navigation and support more content, let's break down the `useful_links.md` into sub-files like `articles.md`, `videos.md` etc

**Comment by M4cs** [comment]
Taking this now!

**Comment by prabhupant** [comment]
Assigning it to you!

**Comment by M4cs** [comment]
I have made a PR, check it out and let me know what you think 👍

**Comment by prabhupant** [comment]
Closed via #88
