### ISSUE TITLE
Add new questions

### ISSUE THREAD

**Issue by prabhupant** [prabhupant/python-ds#9]
Feel free to file a new PR containing new data structures and algorithms questions in Python :)

**Comment by tarungarg2207** [comment]
Hey,
Can you review my PR?
It's about [Luhn Algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm), that is used to validate a variety of identification numbers, such as credit card numbers, IMEI numbers, and National Provider Identifier numbers.
Here is the link for my PR:
https://github.com/prabhupant/python-ds/pull/84

**Comment by prabhupant** [comment]
@tarungarg2207 Yes I have already reviewed it and merged it :)

**Comment by skshahnawaz** [comment]
Please review my PR.
I have added [Rabin-Karp Algorithm](https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm), which is used to search for patterns in a string and return the occurrences.
The link to my PR is : 
#109
